spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/n11_clone}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

app:
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:5173}
