spring:
  application:
    name: n11-clone-api
  autoconfigure:
    exclude: org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

app:
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN}

server:
  error:
    include-message: never
    include-stacktrace: never

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} level=%-5level logger=%logger{36} message=\"%replace(%msg){'\"','\\\"'}\"%n"
